@startuml

state IHMLogin {
  state Login : écran de connexion
}

state IHMSignUp {
  state SignUp : écran d'inscription
}

state IHMAdmin {
  state ConsulterUser: Consulter les utilisateurs
  state ChangerCategorie: Changer la catégorie d'un utilisateurs
  state ConsulterInfosUser: Consulter les informations d'un utilisateur
  state ForcerRetour: Forcer le retour d'un livre

  [*] --> IHMAdherent
  [*] --> ConsulterUser: clique admin
  ConsulterUser --> ChangerCategorie: clique catégorie
  ConsulterUser --> ConsulterInfosUser: clique user
  ConsulterInfosUser --> ForcerRetour: clique return
}

state IHMAdherent {
  state RetourAccueil : Revenir à l'écran d'accueil
  state ChercherLivre : Chercher un livre
  state ChangerPage : Changer la page de livres

  state ConsulterLivre : Consulter un livre
  state DemanderEmprunt : Demander l'emprunt d'un livre
  state RendreLivre : Rendre un livre emprunté
  state ReserverLivre : Reserver un livre
  state CommenterLivre : Commenter un livre

  state ConsulterAuteur : Consulter l'auteur d'un livre

  state LireNotifs: Lire ses notifications non lues
  state ConsulterNotifs : Consulter ses notifications

  state ConsulterInfos : Consulter ses informations
  state ModifierInfos: Modifier ses informations
  state ConsulterEmprunt: Consulter ses emprunts

  [*] --> ChangerPage

  [*] --> ChercherLivre: recherche
  ChercherLivre --> RetourAccueil: clique accueil
  ChercherLivre --> ConsulterNotifs: clique notifs
  ChercherLivre --> ConsulterInfos: clique infos

  [*] --> ConsulterLivre: clique livre
  ConsulterLivre --> DemanderEmprunt: clique emprunt
  ConsulterLivre --> RendreLivre
  ConsulterLivre --> ReserverLivre: clique reservation
  ConsulterLivre --> CommenterLivre: clique commentaire
  ConsulterLivre --> RetourAccueil: clique accueil
  ConsulterLivre --> ChercherLivre: clique recherche
  ConsulterLivre --> ConsulterNotifs: clique notifs
  ConsulterLivre --> ConsulterInfos: clique infos

  ConsulterLivre --> ConsulterAuteur: clique auteur
  ConsulterAuteur --> RetourAccueil: clique accueil
  ConsulterAuteur --> ChercherLivre: clique recherche
  ConsulterAuteur --> ConsulterNotifs: clique notifs
  ConsulterAuteur --> ConsulterInfos: clique infos

  [*] --> LireNotifs: clique notifs
  [*] --> ConsulterNotifs: clique notifs
  ConsulterNotifs --> RetourAccueil: clique accueil
  ConsulterNotifs --> ChercherLivre: clique recherche
  ConsulterNotifs --> ConsulterInfos: clique infos

  [*] --> ConsulterInfos: clique infos
  ConsulterInfos --> ModifierInfos: clique modif
  ConsulterInfos --> ConsulterEmprunt
  ConsulterInfos --> RetourAccueil: clique accueil
  ConsulterInfos --> ChercherLivre: clique recherche
  ConsulterInfos --> ConsulterNotifs: clique notifs

  ConsulterEmprunt --> RendreLivre: clique return

  [*] --> Login: déconnexion
}

[*] --> IHMLogin
IHMLogin --> Login: Connexion
Login --> Login : erreur
Login --> SignUp : Pas de compte
SignUp --> SignUp : erreur
SignUp --> Login : Inscription réussie
Login --> IHMAdmin : Administrateur
Login --> IHMAdherent : Adhérent


@enduml
