@startuml

[*] --> IHMLogin: Lancement

state IHMLogin {
  state Login : écran de connexion

  [*] --> Login: connexion
  Login --> Login: erreur
}

state IHMSignUp {
  state SignUp : écran d'inscription

  [*] --> IHMLogin: connexion
  [*] --> SignUp: inscription
  Login --> IHMSignUp: pas de compte
  SignUp --> SignUp : erreur
  SignUp --> IHMLogin : inscription réussie
}

state IHMAppli {
  state RetourAccueil : Revenir à l'écran d'accueil
  state ChercherLivre : Chercher un livre
  state RechercheAvancée : Recherche avancée d'un livre

  state MenuAdmin : Menu de l'adminstrateur
  state LireNotifs: Lire ses notifications non lues
  state MenuUser : Menu de l'utilisateur

  RetourAccueil --> IHMAccueil: retour à l'accueil
  ChercherLivre --> RechercheAvancée: faire une recherche avancée
  ChercherLivre --> IHMLivre: consulter livre recherché
  RechercheAvancée --> IHMLivre: consulter livre recherché

  MenuAdmin --> IHMAdminUser: consulter les utilisateurs
  MenuAdmin --> IHMAdminLivre: gérer les livres

  LireNotifs --> IHMNotifs: consulter ses notifications

  MenuUser --> IHMUser: consulter son profil
  MenuUser --> IHMLogin: déconnexion
}

state IHMAccueil {
  state ChangerPage: Changer la page de livres

  [*] --> IHMLivre: consulter livre
  [*] --> ChangerPage: changer de page
  Login --> IHMAccueil: connexion réussie
}

state IHMLivre {
  state ConsulterLivre : Consulter un livre
  state DemanderEmprunt : Demander l'emprunt d'un livre
  state RendreLivre : Rendre un livre emprunté
  state ReserverLivre : Reserver un livre
  state CommenterLivre : Commenter un livre
  state DemanderMouvementLivre: Demander le mouvement d'un livre

  [*] --> ConsulterLivre
  ConsulterLivre --> DemanderEmprunt: clique emprunt
  ConsulterLivre --> RendreLivre
  ConsulterLivre --> ReserverLivre: clique reservation
  ConsulterLivre --> CommenterLivre: clique commentaire
  ConsulterLivre --> DemanderMouvementLivre: clique demande

  ConsulterLivre --> IHMAuteur: consulter auteur
}

state IHMAuteur {
  state ConsulterAuteur : Consulter l'auteur d'un livre

  [*] --> ConsulterAuteur
  ConsulterAuteur --> IHMLivre: consulter livre auteur
}

state IHMUser {
  state ConsulterInfos: Consulter ses informations
  state ModifierInfos: Modifier ses informations
  state ConsulterEmprunt: Consulter ses emprunts

  [*] --> ConsulterInfos
  ConsulterInfos --> ModifierInfos: clique modif

  [*] --> ConsulterEmprunt
  ConsulterEmprunt --> RendreLivre: clique return
}

state IHMAdminUser {
  state ConsulterUser: Consulter les utilisateurs
  state ChangerCategorie: Changer la catégorie d'un utilisateurs
  state ForcerRetour: Forcer le retour d'un livre

  [*] --> ChangerCategorie: clique catégorie
  [*] --> ConsulterUser: clique admin user
  ConsulterUser --> IHMUser: consulter user
  ConsulterUser --> ForcerRetour: clique return
  ForcerRetour --> RendreLivre: clique return
}

state IHMAdminLivre {
  state DeplacerLivre: déplacer un livre
  state AjouterLivre: ajouter un livre

  [*] --> DeplacerLivre: clique déplacer
  [*] --> AjouterLivre: clique ajouter
}

state IHMNotifs {
  state ConsulterNotifs : Consulter ses notifications

  [*] --> ConsulterNotifs: consulter ses notifications
}


@enduml
