@startuml

state IHMLogin {
  state Login : écran de connexion
}

state IHMSignUp {
  state SignUp : écran d'inscription
}

state IHMAdmin {
  state Initialisation : Initialisation de la bibliothèque
  state CreerBibliotheque : Créer une nouvelle bibliothèque
  state ImporterBibliotheque : Importer une bibliothèque du disque
  state BibliothequeChargee : Bibliothèque chargée
  state GererLivres : Gérer les livres
  state GererUtilisateurs : Gérer les utilisateurs
  state GererEmprunts : Gérer les emprunts

  [*] --> Initialisation
}

state IHMAdherent {
  state ChercherLivre : Chercher un livre
  state DemanderEmprunt : Demander l'emprunt d'un livre
  state GererInfos : Gérer ses informations

  [*] --> ChercherLivre
  [*] --> DemanderEmprunt
  [*] --> GererInfos
}

[*] --> IHMLogin
IHMLogin --> Login: Connexion
Login --> Login : erreur
Login --> SignUp : Pas de compte
SignUp --> SignUp : erreur
SignUp --> Login : Inscription réussie
Login --> IHMAdmin : Administrateur
Login --> IHMAdherent : Adhérent


Initialisation --> CreerBibliotheque : Créer une nouvelle bibliothèque
Initialisation --> ImporterBibliotheque : Importer une bibliothèque du disque
Initialisation --> BibliothequeChargee : Bibliothèque chargée
BibliothequeChargee --> GererLivres : Gérer les livres
BibliothequeChargee --> GererUtilisateurs : Gérer les utilisateurs
BibliothequeChargee --> GererEmprunts : Gérer les emprunts


@enduml
