@startuml

interface Personne {
    String nom
    String prenom
}
abstract class Utilisateur {
    String mail
    int id
    userCat categorie

    void emprunteLivre()
    void retourneLivre()
    String[] voirInfos()
    Livre[] voirEmprunts()
}

class Categorie {
    String nom
    int empruntMax
    int dureeMax
}

class Auteur {
    int naissance
}

class Bibliothecaire {
    void ajouterLivre()
    void supprimerLivre()
    void ajouterAdherent()
    void supprimerAdherent()
    Adherent[] voirAdherents()
    String[] voirInfosAdherents(Adherent a)
}

Personne <|-- Utilisateur
Personne <|-- Auteur

Utilisateur <|-- Adherent
Utilisateur <|-- Bibliothecaire

class Emprunt {
    String date
    Livre livre
    Utilisateur user
}

class Interdiction {
    String date
    Utilisateur user
}

class Livre {
    Edition[] edition
    String titre
    Auteur[] auteur
    int annee
    String[] mots-clés
}

class Edition {
    String editeur
    int annee
    int isbn
}

class bibliController {
    Buttons[] bouttons
}

Livre "1 ... n" o--o "1 ... 1" Edition : est édité
Livre "1 ... n" o--o "1 ... n" Auteur : a écrit
Livre "0 ... n" o--o "1 ... 1" Emprunt : emprunté

Emprunt "1 ... 1" o--o "0 ... n" Utilisateur : a emprunté
Categorie "0 ... n" o--o "1 ... 1" Utilisateur : est catégorisé
Interdiction "1 ... 1" o--o "0 ... 1" Utilisateur : est interdit

@enduml