@startuml

left to right direction

actor Utilisateur as User

rectangle "Authentification" {
    User--> (Login)
    (Login)--> User: erreur
    (Login)-->"Adhérent": Authentification adhérent
    (Login)-->"Bibliothécaire": Authentification admin
}

rectangle "Système de la Bibliothèque" {
    rectangle "Gestion des livres" {
        "Adhérent" --> (Consulter la liste des livres disponibles)
        "Bibliothécaire" --> (Consulter la liste des livres disponibles)

        "Adhérent" --> (Rechercher un livre)
        "Bibliothécaire" --> (Rechercher un livre)

        "Adhérent" --> (Emprunter un livre)
        "Bibliothécaire" --> (Emprunter un livre)

        "Adhérent" --> (Retourner un livre)
        "Bibliothécaire" --> (Retourner un livre)
    }

    rectangle "Gestion du compte" {
        "Adhérent" --> (Déconnexion)
        "Bibliothécaire" --> (Déconnexion)
        (Déconnexion)--> Authentification

        "Adhérent" --> (Consulter ses informations personnelles)
        "Bibliothécaire" --> (Consulter ses informations personnelles)

        "Adhérent" --> (Consulter ses emprunts)
        "Bibliothécaire" --> (Consulter ses emprunts)
    }

    rectangle "Administration" {
        "Bibliothécaire" --> (Ajouter un nouveau livre)
        "Bibliothécaire" --> (Supprimer un livre)
        "Bibliothécaire" --> (Lister les adhérents et voir leurs informations personnelles)
        "Bibliothécaire" --> (Créer un nouvel adhérent)
        "Bibliothécaire" --> (Supprimer un adhérent)
    }
}

@enduml
